version: "3.8"
services:
  springapp:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: springboot
    container_name: myapp
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    environment:
     - spring.datasource.url=jdbc:postgresql://postgres:5432/bashdb
     - spring.datasource.username=postgres
     - spring.datasource.password=root
    networks:
      - my-network
  postgres:
    image: postgres:15
    container_name: mypostgress
    ports:
     - "5432:5432"
    environment:
      POSTGRES_DB: bashdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - my-network
    volumes:
       -  C://bash/data:/var/lib/postgresql/data


networks:
   my-network:
     driver: bridge
